name: Blox Fruits Stock Checker
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:
jobs:
  check-stock:
    runs-on: ubuntu-latest
    steps:
      - name: Repoyu Klonla
        uses: actions/checkout@v3
      - name: Python'u Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Kütüphaneleri ve Tarayıcıyı Kur
        run: |
          pip install -r requirements.txt
          playwright install chromium
      - name: Script'i Çalıştır
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python main.py
